export enum UmrahStatus {
  RECEIVING_OFFERS = "0",
  OFFER_ACCEPTED = "1",
  AWAITING_PAYMENT = "2",
  PAYMENT_COMPLETED = "3",
  PAYMENT_FAILED = "4",
  ACCEPTED = "5",
  STARTING_SOON = "6",
  IN_PROGRESS = "7",
  COMPLETED = "8",
  CANCELLED_BY_PERFORMER = "9",
  CANCELLED_BY_SEEKER = "10",
  CANCELLED_BY_ADMIN = "11",
  REQUEST_EXPIRED = "12",
}
export enum UmrahAction {
  UMRAH_REQUEST_CREATED = "0",
  OFFERS_RECEIVING_STARTED = "1",
  OFFER_REJECTED = "2",
  OFFER_ACCEPTED = "3",
  OFFER_DECLINED = "4",

  AWAITING_PAYMENT = "5",
  PAYMENT_SUCCESSFUL = "6",
  PAYMENT_FAILED = "7",

  REQUEST_CONFIRMED = "8",
  REQUEST_STARTING_SOON = "9",
  REQUEST_IN_PROGRESS = "10",
  REQUEST_COMPLETED = "11",

  PERFORMER_ASSIGNED = "12",
  PERFORMER_CHANGED = "13",

  CANCELLED_BY_PERFORMER = "14",
  CANCELLED_BY_SEEKER = "15",
  CANCELLED_BY_ADMIN = "16",

  REQUEST_EXPIRED = "17",

  SYSTEM_AUTO_CANCELLED = "18",
  SYSTEM_AUTO_EXPIRED = "19",
  START_IHRAM = "20",
  START_TAWAF = "21",
  START_SAI = "22",
  END_IHRAM = "23",
  END_TAWAF = "24",
  END_SAI = "25",
}
export enum OfferStatus {
  PENDING = "0",
  ACCEPTED = "1",
  REJECTED = "2",
  CANCELLED = "3",
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}
export enum PersonStatus {
  MYSELF = '0',
  SICK = '1',
  DISABLED = '2',
  DECEASED = '3',
  OTHER = '4',
}
